---
title: "PSY 8960 Final Project Shiny App Notebook"
author: "Isaac Bazian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Script Settings and Resources**

```{r script_settings_and_resources, message=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
```


## **Data Import and Cleaning**

```{r data_import}
finalproj_full_tbl <- readRDS("../data/finalproj_data.rds")

finalproj_skinny_tbl <- finalproj_full_tbl %>% 
  select(MonthlyIncome, Attrition, JobSatisfaction, Department, EducationField, Gender, JobRole) %>% 
  mutate(Attrition = case_match(Attrition, "Yes" ~ 1, "No" ~ 0)) #Also makes the column numeric

saveRDS(finalproj_skinny_tbl, "../shiny/people_dashboard/finalshinydata.rds") #This code takes the skinny data and stores it for use in the shiny app
```





## Testing

```{r}

chosen_outcome <- "Attrition"
ggplot(finalproj_skinny_tbl, aes(x = .data[[chosen_outcome]])) + 
        geom_bar()
```


```{r}

chosen_outcome <- "MonthlyIncome"

filters_used <- c("Gender", "EducationField")

finalproj_skinny_tbl %>%
  group_by(NULL) %>% 
  summarise("Mean" = mean(.data[[chosen_outcome]]), "Standard Deviation" = sd(.data[[chosen_outcome]]))

finalproj_skinny_tbl %>% 
  group_by(across(all_of(filters_used))) %>% 
  summarise("Mean" = mean(.data[[chosen_outcome]]), "Standard Deviation" = sd(.data[[chosen_outcome]]))
```






